### ISSUE TITLE
Failed to decode bad request response

### ISSUE THREAD

**Issue by octlabs** [passbolt/mobile-passbolt-ios#2]
## ISSUE
* Passbolt Version: 3.5.0 / 3.5.0
* Platform and Target: Passbolt/566 CFNetwork/1329 Darwin/21.3.0
iPhone13,3
OS 15.3.1
App 1.4.0

### What you did
No list update after beta. Install latest server (git master) und ios app.
Unregister und Reregister in App
Server debug on

### What happened
No entrys, Network error
Server logs/ ist empty

### Logs
[2022-03-05 15:47:40] Beginning authorization...
[2022-03-05 15:47:40] ...using biometrics...
[2022-03-05 15:47:40] ...account passphrase found...
[2022-03-05 15:47:40] ...account private key found...
[2022-03-05 15:47:40] Refreshing session...
[2022-03-05 15:47:40] ... session refresh not required, reusing current session!
[2022-03-05 15:47:40] ...authorization succeeded!
[2022-03-05 15:48:39] Beginning authorization...
[2022-03-05 15:48:39] ...using biometrics...
[2022-03-05 15:48:40] ...account passphrase found...
[2022-03-05 15:48:40] ...account private key found...
[2022-03-05 15:48:40] Refreshing session...
[2022-03-05 15:48:40] ... session refresh not required, reusing current session!
[2022-03-05 15:48:40] ...authorization succeeded!
[2022-03-05 15:48:41] Verifying data integrity...
[2022-03-05 15:48:41] ...data integrity verification finished
[2022-03-05 15:48:41] Fetching server configuration...
[2022-03-05 15:48:42] ...server configuration fetched!
[2022-03-05 15:48:42] Failed to decode bad request response
[2022-03-05 15:48:44] Beginning authorization...
[2022-03-05 15:48:44] ...using biometrics...
[2022-03-05 15:48:44] ...account passphrase found...
[2022-03-05 15:48:44] ...account private key found...
[2022-03-05 15:48:44] Refreshing session...
[2022-03-05 15:48:44] ... session refresh not required, reusing current session!
[2022-03-05 15:48:44] ...authorization succeeded!
[2022-03-05 15:48:48] Failed to decode bad request response

 ### Healthcheck shell
-------------------------------------------------------------------------------

 Environment

 [PASS] PHP version 7.4.19.
 [PASS] PCRE compiled with unicode support.
 [PASS] The temporary directory and its content are writable and not executable.
 [PASS] The logs directory and its content are writable.
 [PASS] GD or Imagick extension is installed.
 [PASS] Intl extension is installed.
 [PASS] Mbstring extension is installed.

 Config files

 [PASS] The application config file is present
 [PASS] The passbolt config file is present

 Core config

 [FAIL] Debug mode is on.
 [HELP] Set debug = false; in config/passbolt.php
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Full base url is set to https://passbolt.foo.com
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.

 SSL Certificate

 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [PASS] Not using a self-signed certificate

 Database

 [PASS] The application is able to connect to the database
 [PASS] 26 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded.
 [PASS] The environment variable GNUPGHOME is set to /homes/foo/.gnupg.
 [PASS] The directory /homes/fooooooo/.gnupg containing the keyring is writable by the webserver user.
 [PASS] The server OpenPGP key is not the default one
 [PASS] The public key file is defined in config/passbolt.php and readable.
 [PASS] The private key file is defined in config/passbolt.php and readable.
 [PASS] The server key fingerprint matches the one defined in config/passbolt.php.
 [PASS] The server public key defined in the config/passbolt.php (or environment variables) is in the keyring.
 [PASS] There is a valid email id defined for the server key.
 [PASS] The public key can be used to encrypt a message.
 [PASS] The private key can be used to sign a message.
 [PASS] The public and private keys can be used to encrypt and sign a message.
 [PASS] The private key can be used to decrypt a message.
 [PASS] The private key can be used to decrypt and verify a message.
 [PASS] The public key can be used to verify a signature.
 [PASS] The server public key format is Gopengpg compatible.
 [PASS] The server private key format is Gopengpg compatible.

 Application configuration

 [PASS] Using latest passbolt version (3.5.0).
 [PASS] Passbolt is configured to force SSL use.
 [PASS] App.fullBaseUrl is set to HTTPS.
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app
 [PASS] All email notifications will be sent.

 JWT Authentication

 [PASS] The JWT Authentication plugin is enabled
 [PASS] The /homes/foo/passbolt.foo.com/passbolt/config/jwt/ directory is not writable.
 [PASS] A valid JWT key pair was found

 [FAIL] 1 error(s) found. Hang in there!

**Comment by gothickitty93** [comment]
Hello, 

I am having this issue as well since today's update. However, I'm am running iOS 17

**Comment by KaQuMiQ** [comment]
Hi, thanks for reaching out. Just to be sure - you are referring to current main branch on github (which is v1.5.0, there should be an update on github soon) or latest AppStore (which is 1.14.2)?

**Comment by gothickitty93** [comment]
Sorry, I should have specified. It's the App Store version 1.14.2

**Comment by danvoid** [comment]
Hi, getting the same issue on **iOS 17**.. any fix?
![photo_2023-07-16_12-03-59](https://github.com/passbolt/mobile-passbolt-ios/assets/100365818/35e7a8c0-2288-4049-a9f5-e3bb6c852922)

**Comment by Underlyingglitch** [comment]
I have the same problem, also running iOS 17

**Comment by sbrkx** [comment]
Same problem, running iOS 17 Beta 2

**Comment by gw86** [comment]
> Sorry, I should have specified. It's the App Store version 1.14.2

@gothickitty93 your issue should not appear in the currently available app version 1.14.4 on iOS 15.x and 16.x. Please let us know if it appears otherwise.

**Comment by gw86** [comment]
@sbrkx @Underlyingglitch @danvoid @gothickitty93 this issue should not appear in the currently available app version 1.14.4 on iOS 15.x and 16.x. Please let us know if it appears otherwise.

The fix for iOS 17 is on its way but won't be available before app version 1.15.0 is released. I have tested it on iOS 17 Beta 2, and all resources are available. However, until the official iOS 17 release, we cannot guarantee that other (less spectacular) things will be working.

**Comment by KaQuMiQ** [comment]
Passbolt iOS application version 1.15.0 is now available on the AppStore. It should fix this issue on iOS 17.

For those interested in details - on iOS 17 Apple has changed implementation of parts of the Foundation framework to its open source counterpart: https://github.com/apple/swift-corelibs-foundation . That caused the behavior change of some of the functions. It this case - JSONDecoder class behaves differently than its objc counterpart which resulted in data decoding error.
