### ISSUE TITLE
As a mobile user I should be able to configure my account without camera

### ISSUE THREAD

**Issue by Fridasbabe** [passbolt/mobile-passbolt-ios#5]
## Scanning QR code
* Passbolt Version: [PASS] Using latest passbolt version (4.3.0).
* Platform and Target:
  -- etc.: iOS 16

Phone doesn't have working camera, this makes it impossible to add mobile phone, also there should be possible to add new user only using the phone app. Is this something that can be worked on?

**Comment by stripthis** [comment]
Hello,

This feature is available on Android but currently not implemented on iOS.
It will be implemented at some point when we catch up with feature parity on iOS.

Cheers

**Comment by Fridasbabe** [comment]
That sounds good, i understand there still development. Seems to head the right direction too.

Cheers

**Comment by scadra** [comment]
@Fridasbabe,

You are now able to configure your mobile application without using a QR code. It was released on the version 1.17.4. 

To do it : 
- Export the account kit from the web application, [check out the documentation](https://www.passbolt.com/docs/user/quickstart/desktop/windows-app/). This account kit was implemented for the desktop app needs and works for the mobile apps. Later we will make it clearer and document it.
- Transfer your account kit on your phone
 - On the IOS application while associating a new account, click on the help icon on the top right. 
 - In the menu that opened click on the import account kit and choose the file previously saved on your phone
